font pango:Sans 12

# Monitor Layout
exec --no-startup-id xrandr --output HDMI-1-1 --mode 1920x1080 --rate 60 --primary

# I3 Setup
exec --no-startup-id dex-autostart --autostart --environment i3
exec --no-startup-id picom
exec --no-startup-id unclutter -idle 1 -root

# Wallpaper
exec_always --no-startup-id feh --bg-fill ~/.config/i3/wallpaper.jpg

# Startup Workspaces Setup
assign [class="Alacritty"] workspace 1
assign [class="zen"] workspace 2
assign [class="Spotify"] workspace 3

exec alacritty
exec zen-browser
exec spotify-launcher
