#!/usr/bin/env bash

playerctl -p "mprisence_web.youtube_music" metadata --follow --format "{{ title }}|||{{ artist }}" | while read -r line; do
    title="${line%%|||*}"
    artist="${line##*|||}"

    if [ -z "$title" ] || [ -z "$artist" ]; then
        echo ""
    else
        echo " $artist - $title"
    fi
done
