#!/usr/bin/env bash

if command -v pacman >/dev/null 2>&1; then
  sudo pacman -S --noconfirm --needed vim
fi

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
