#!/usr/bin/env bash
set -euo pipefail

NEOVIM_VERSION="v0.12.2"

sudo pacman -S --noconfirm --needed base-devel cmake ninja curl git gettext unzip xclip ripgrep \
  nodejs npm typescript prettier go python python-black pgformatter opam stylua \
  typescript-language-server bash-language-server pyright lua-language-server clang gopls

go install github.com/sqls-server/sqls@latest

sudo npm install -g vscode-langservers-extracted @astrojs/language-server

if command -v nvim >/dev/null 2>&1; then
  echo "Neovim is already installed. Skipping."
else
  echo "Building Neovim $NEOVIM_VERSION..."

  mkdir -p "$HOME/personal"

  if [ ! -d "$HOME/personal/neovim" ]; then
    git clone -b "$NEOVIM_VERSION" https://github.com/neovim/neovim.git "$HOME/personal/neovim"
  fi

  cd "$HOME/personal/neovim"
  git fetch --tags
  git checkout "$NEOVIM_VERSION"

  make CMAKE_BUILD_TYPE=RelWithDebInfo
  sudo make install
fi

if ! command -v rustup >/dev/null 2>&1; then
  curl https://sh.rustup.rs -sSf | sh -s -- -y
  rustup default stable
fi

export PATH="$HOME/.cargo/bin:$PATH"

source "$HOME/.cargo/env"
rustup component add rust-analyzer

if ! command -v tree-sitter >/dev/null 2>&1; then
  cargo install tree-sitter-cli
fi

if [ ! -d "$HOME/.opam" ]; then
  opam init -y --disable-sandboxing
fi

eval "$(opam env)"
opam install -y ocaml-lsp-server ocamlformat
