#!/usr/bin/env bash

sudo pacman -S --noconfirm --needed xorg-server xorg-xinit xorg-xinput xorg-xrandr xdg-utils xclip \
  i3-wm i3lock picom polybar rofi feh brightnessctl dunst unclutter scrot playerctl \
  noto-fonts noto-fonts-cjk noto-fonts-extra ttf-jetbrains-mono-nerd papirus-icon-theme \
  alacritty spotify-launcher thunar caligula htop fastfetch

if command -v yay >/dev/null 2>&1; then
  yay -S --noconfirm --needed zen-browser-bin
fi
