#!/usr/bin/env bash

sudo pacman -S --noconfirm --needed xorg-server xorg-xinit xorg-xrandr xdg-utils xclip \
  i3-wm i3lock picom rofi feh brightnessctl ly dunst unclutter scrot \
  noto-fonts noto-fonts-cjk noto-fonts-extra ttf-jetbrains-mono-nerd papirus-icon-theme \
  alacritty spotify-player thunar caligula htop fastfetch

sudo systemctl enable ly@tty1

loginctl enable-linger "$USER"

if command -v yay >/dev/null 2>&1; then
  yay -S --noconfirm --needed zen-browser-bin
fi
