#!/usr/bin/env bash

selected=$(dedoc list --local --porcelain | fzf --layout=reverse --prompt="Language > ")
[ -z "$selected" ] && exit 0

page=$(dedoc search --porcelain "$selected" | fzf --layout=reverse --prompt="Page > ")
[ -z "$page" ] && exit 0

content=$(dedoc open "$selected" "$page")

if bat --list-languages | grep -qi "\b${selected}\b"; then
  echo "$content" | bat -l "$selected" --style=plain --paging=always --pager "less -RX"
else
  echo "$content" | less -RX
fi
