font pango:Sans 12

output eDP-1 disable

input "type:touchpad" {
    natural_scroll enabled
}

seat seat0 hide_cursor 1000

exec dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY SWAYSOCK XDG_CURRENT_DESKTOP=sway:GNOME

exec_always --no-startup-id launch-waybar

exec swaybg -i ~/.config/sway/wallpaper.jpg -m fill

# Startup Workspaces Setup
assign [app_id="Alacritty"] 1
assign [app_id="zen"] 2
assign [app_id="spotify"] 3

exec alacritty
exec zen-browser
exec spotify-launcher
