font pango:Sans 12

output eDP-1 disable

input "type:touchpad" {
    natural_scroll enabled
}

seat seat0 hide_cursor 1000

exec dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY SWAYSOCK XDG_CURRENT_DESKTOP=sway:GNOME

exec_always --no-startup-id launch-waybar

exec --no-startup-id swaybg -i ~/.config/sway/wallpaper.jpg -m fill

exec --no-startup-id swayidle -w \
    timeout 600 'swaylock -f -c 282C34' \
    timeout 900 'swaymsg "output * power off"' \
        resume 'swaymsg "output * power on"' \
    before-sleep 'swaylock -f -c 282C34'

# Startup Workspaces Setup
assign [app_id="Alacritty"] 1
assign [app_id="chromium"] 2

exec alacritty
exec chromium
